### ISSUE TITLE
Use new Adafruit python libraries

### ISSUE THREAD

**Issue by camrex** [switchdoclabs/RaspberryPi-WeatherPiArduinoV2#1]
Why not use Adafruit's updated python libraries, that have an install, thus no need to have them contained within the WeatherPi project, and can thus be used outside WeatherPi. Also gets rid of the need of calling them via a sys.path.append. 

The same can be done for the AS3935.

**Comment by switchdoclabs** [comment]
Perfectly reasonable suggestion.

The two reasons why we don't do that are:

1) Adafruit has been changing their software structures, and that breaks things.  (Adafruit Unified Sensors for one example).  Yes, this forces us to do a hand update when things change, but again, then we have control over the code.

2) There are problems with the Adafruit libraries which we have to correct to make things work correctly sometimes with our hardware (and sometimes with others).   Rather than fork the Adafruit libraries and build more libraries, we find it easier to copy them to the directory and use the local copy.   That way we KNOW what we are getting.   We do contribute back to Adafruit the problems we find that are applicable, but it is a long route to wait until it is in the merged library.

So, yes in general, it is better to link to the main library but we have chosen this route for the weather software as it tends to be around a long time.

**Comment by camrex** [comment]
Logical explanation. As such I will close the issue.
